language: c

sudo: false

matrix:
  include:
    - env: LUA="lua 5.1"
    # - env: LUA="lua 5.1"
    # - env: LUA="lua 5.2"
    # - env: LUA="lua 5.3"
    # - env: LUA="luajit 2.0"
    # - env: LUA="luajit 2.1"

services:
  - redis-server

branches:
  only:
    - master

before_install:
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - bash .travis/setup_uv.sh

install:
  - luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks install bgcrypto-sha --server=http://luarocks.org/dev
  - luarocks install lluv-redis --server=http://luarocks.org/dev
  - luarocks install luaposix
  - luarocks make rockspecs/lluv-qless-scm-0.rockspec

before_test:
  - luarocks install lua_cliargs 2.5
  - luarocks install lluv-busted --server=http://luarocks.org/dev

script:
  - busted_bootstrap

notifications:
  email:
    on_success: change
    on_failure: always
